const AREAS = {
  anatomia: {
    label: 'Anatomia',
    icon: '🩻',
    modules: [
      {
        id: 'planos_eixos',
        icon: '📐',
        color: '#e8f6ef',
        title: 'Planos e Eixos',
        subtitle: 'Posição anatômica, planos e movimentos',
        questions: [
          {q:'A posição anatômica padrão descreve o indivíduo:',options:['Deitado em decúbito dorsal','Em pé, face para frente, palmas para frente','Sentado com joelhos a 90°','Deitado em decúbito ventral'],answer:1,explain:'Em pé, olhando para frente, membros ao lado do corpo e palmas voltadas anteriormente.'},
          {q:'Qual plano divide o corpo em porções anterior e posterior?',options:['Sagital','Transversal','Frontal (coronal)','Oblíquo'],answer:2,explain:'O plano frontal ou coronal divide o corpo em partes anterior e posterior.'},
          {q:'O plano sagital mediano divide o corpo em:',options:['Superior e inferior','Anterior e posterior','Direita e esquerda','Proximal e distal'],answer:2,explain:'O plano sagital mediano divide o corpo em metades direita e esquerda simétricas.'},
          {q:'O plano transversal é também chamado de:',options:['Plano frontal','Plano horizontal','Plano coronal','Plano sagital'],answer:1,explain:'O plano transversal ou horizontal divide o corpo em partes superior e inferior.'},
          {q:'Flexão e extensão do joelho ocorrem no plano:',options:['Frontal','Transversal','Sagital','Oblíquo'],answer:2,explain:'Flexão e extensão são movimentos que ocorrem no plano sagital.'},
          {q:'Abdução e adução do quadril ocorrem no plano:',options:['Sagital','Frontal','Transversal','Horizontal'],answer:1,explain:'Abdução e adução ocorrem no plano frontal, afastando ou aproximando da linha média.'},
          {q:'Rotações (medial e lateral) ocorrem no plano:',options:['Sagital','Frontal','Transversal','Oblíquo'],answer:2,explain:'As rotações ocorrem em torno de um eixo longitudinal no plano transversal.'},
          {q:'O movimento de afastar o membro da linha média chama-se:',options:['Adução','Abdução','Rotação medial','Flexão'],answer:1,explain:'Abdução é o movimento de afastamento da linha média do corpo.'},
          {q:'O movimento de aproximar o membro da linha média chama-se:',options:['Abdução','Extensão','Adução','Rotação lateral'],answer:2,explain:'Adução é o movimento de aproximação em direção à linha média do corpo.'},
          {q:'O esterno está _______ em relação à coluna vertebral:',options:['Posterior','Lateral','Superior','Anterior'],answer:3,explain:'O esterno é anterior (ventral) em relação à coluna vertebral.'},
          {q:'O tornozelo é _______ em relação ao joelho:',options:['Proximal','Superior','Distal','Medial'],answer:2,explain:'O tornozelo está mais distante da raiz do membro, sendo distal ao joelho.'},
          {q:'Cranial indica posição:',options:['Mais próxima dos pés','Mais próxima da cabeça','Mais lateral','Mais posterior'],answer:1,explain:'Cranial (cefálico) indica proximidade em direção à cabeça.'},
          {q:'Lateral significa:',options:['Próximo à linha média','Afastado do plano mediano','Acima de outra estrutura','Distal'],answer:1,explain:'Lateral indica afastamento do plano mediano do corpo.'},
          {q:'Medial significa:',options:['Afastado da linha média','Próximo à linha média','Inferior','Posterior'],answer:1,explain:'Medial indica proximidade à linha média do corpo.'},
          {q:'Ipsilateral significa:',options:['No lado oposto','No mesmo lado do corpo','Na linha média','Distal'],answer:1,explain:'Ipsilateral refere-se a estruturas do mesmo lado do corpo.'},
          {q:'Contralateral significa:',options:['No mesmo lado','No lado oposto','Superior','Proximal'],answer:1,explain:'Contralateral refere-se a estruturas de lados opostos do corpo.'},
          {q:'O eixo em torno do qual ocorrem flexão e extensão é:',options:['Longitudinal','Ântero-posterior','Médio-lateral (transverso)','Oblíquo'],answer:2,explain:'Flexão e extensão ocorrem em torno do eixo médio-lateral (transverso).'},
          {q:'Supinação do antebraço é um movimento que ocorre no plano:',options:['Sagital','Frontal','Transversal','Coronal'],answer:2,explain:'Supinação e pronação são rotações que ocorrem no plano transversal.'},
          {q:'Qual termo indica estrutura mais próxima da superfície corporal?',options:['Profundo','Superficial','Medial','Distal'],answer:1,explain:'Superficial indica proximidade à superfície externa do corpo.'},
          {q:'O plano sagital paralelo ao mediano, mas deslocado lateralmente, é chamado de:',options:['Plano sagital mediano','Plano parassagital','Plano coronal','Plano horizontal'],answer:1,explain:'Planos sagitais que não passam pela linha média são chamados parassagitais.'},
        ]
      },
      {
        id: 'acidentes_osseos',
        icon: '🦴',
        color: '#f4fff2',
        title: 'Acidentes Ósseos',
        subtitle: 'Proeminências, depressões e forames',
        questions: [
          {q:'Saliências ósseas de inserção de tendões e ligamentos são chamadas de:',options:['Fossas','Côndilos','Tuberosidades','Forames'],answer:2,explain:'Tuberosidades são saliências rugosas para inserção muscular e ligamentar.'},
          {q:'Pequena proeminência óssea arredondada:',options:['Túber','Cabeça','Tubérculo','Espinha'],answer:2,explain:'Tubérculo é uma pequena saliência óssea arredondada.'},
          {q:'Superfície articular arredondada no final de osso longo:',options:['Epicôndilo','Côndilo','Crista','Linha'],answer:1,explain:'Côndilos são superfícies articulares arredondadas que se articulam com outros ossos.'},
          {q:'Abertura óssea para passagem de vasos e nervos:',options:['Fossa','Sulco','Forame','Espinha'],answer:2,explain:'Forame é a abertura óssea que permite passagem de estruturas neurovasculares.'},
          {q:'Depressão alongada em um osso:',options:['Fissura','Sulco','Espinha','Linha'],answer:1,explain:'Sulco é uma depressão alongada percorrida por tendões, vasos ou nervos.'},
          {q:'Grande proeminência óssea do fêmur proximal:',options:['Côndilo','Cabeça','Trocanter','Tubérculo'],answer:2,explain:'O fêmur possui grande e pequeno trocanter, grandes proeminências proximais.'},
          {q:'Porção esférica articular de ossos como úmero e fêmur:',options:['Cabeça','Fissura','Linha','Crista'],answer:0,explain:'A cabeça é a porção esférica articular de ossos longos como úmero e fêmur.'},
          {q:'Proeminência óssea estreita e pontiaguda:',options:['Linha','Crista','Espinha','Tuberosidade'],answer:2,explain:'Espinha óssea é uma projeção fina e pontiaguda.'},
          {q:'Área ampla e levemente elevada para inserção muscular:',options:['Tuberosidade','Fossa','Cabeça','Fissura'],answer:0,explain:'Tuberosidade é uma grande elevação rugosa para inserção muscular.'},
          {q:'Cavidade rasa e alargada em um osso:',options:['Fossa','Forame','Sulco','Crista'],answer:0,explain:'Fossas são depressões rasas, como a fossa supraespinhal da escápula.'},
          {q:'Processo vertebral palpável posteriormente ao longo da coluna:',options:['Côndilo occipital','Processo espinhoso','Cabeça do fêmur','Tubérculo maior'],answer:1,explain:'Os processos espinhosos projetam-se posteriormente e são palpáveis ao longo da coluna.'},
          {q:'Pequenas superfícies articulares planas das vértebras torácicas:',options:['Facetas articulares','Tubérculos','Trocanteres','Linhas'],answer:0,explain:'Facetas articulares são superfícies planas para articulação costo-vertebral.'},
          {q:'O acrômio é um exemplo de:',options:['Tubérculo','Processo','Forame','Fossa'],answer:1,explain:'O acrômio é um processo da escápula que forma o ponto mais alto do ombro.'},
          {q:'O sulco intertubercular do úmero abriga:',options:['Nervo radial','Tendão do bíceps braquial (cabeça longa)','Veia basílica','Nervo mediano'],answer:1,explain:'O sulco intertubercular (bicipital) abriga o tendão da cabeça longa do bíceps.'},
          {q:'A crista ilíaca é um exemplo de:',options:['Sulco','Forame','Crista','Côndilo'],answer:2,explain:'A crista ilíaca é uma crista óssea superior do osso ilíaco, palpável lateralmente.'},
          {q:'O processo estilóide é encontrado em:',options:['Fêmur','Rádio e ulna distais','Tíbia proximal','Escápula'],answer:1,explain:'Processos estilóides são encontrados no rádio e na ulna distais.'},
          {q:'Qual acidente ósseo forma a goteira do nervo radial no úmero?',options:['Sulco intertubercular','Sulco do nervo radial (goteira de torção)','Forame supracondilar','Fossa coronoide'],answer:1,explain:'O sulco do nervo radial (goteira de torção) percorre a face posterior do úmero.'},
          {q:'O tubérculo maior (troquiter) do úmero é ponto de inserção de:',options:['Deltóide e peitoral maior','Manguito rotador (supraespinhal, infraespinhal, redondo menor)','Bíceps e coracobraquial','Tríceps braquial'],answer:1,explain:'O tubérculo maior recebe inserção dos músculos supraespinhal, infraespinhal e redondo menor.'},
          {q:'A sínfise púbica é classificada como qual tipo de acidente ósseo/articulação?',options:['Diartrose sinovial','Anfiartroses (sínfise)','Sutura','Gonfose'],answer:1,explain:'A sínfise púbica é uma anfiartroses com disco fibrocartilaginoso entre os ossos púbicos.'},
          {q:'O forame obturado é encontrado em qual osso?',options:['Sacro','Osso coxal (ilíaco)','Fêmur','Tíbia'],answer:1,explain:'O forame obturado é uma grande abertura no osso coxal, delimitada pelo púbis e ísquio.'},
        ]
      },
      {
        id: 'segmentos',
        icon: '🧍',
        color: '#eaf1ff',
        title: 'Segmentos Corporais',
        subtitle: 'Divisão e nomenclatura regional',
        questions: [
          {q:'A divisão básica do corpo humano inclui:',options:['Crânio, tórax e pelve apenas','Cabeça, pescoço, tronco e membros','Membros superiores e inferiores apenas','Tórax e abdome apenas'],answer:1,explain:'A divisão clássica inclui cabeça, pescoço, tronco (tórax, abdome, pelve) e membros.'},
          {q:'O tronco é composto por:',options:['Cabeça e pescoço','Tórax, abdome e pelve','Mãos e pés','Coxa e perna'],answer:1,explain:'Tronco compreende tórax, abdome e pelve/região glútea.'},
          {q:'O antebraço localiza-se entre:',options:['Braço e mão','Mão e ombro','Coxa e perna','Perna e pé'],answer:0,explain:'O antebraço está entre o braço (proximal) e a mão (distal).'},
          {q:'Anatomicamente, a perna localiza-se entre:',options:['Quadril e joelho','Joelho e tornozelo','Tornozelo e pé','Coxa e quadril'],answer:1,explain:'Perna é o segmento entre joelho e tornozelo. Entre quadril e joelho é a coxa.'},
          {q:'A região plantar refere-se à:',options:['Sola do pé','Dorso da mão','Face anterior da perna','Face posterior do tronco'],answer:0,explain:'Plantar refere-se à face inferior (sola) do pé.'},
          {q:'A região palmar corresponde à:',options:['Dorso do pé','Face anterior da mão','Face posterior da perna','Região cervical'],answer:1,explain:'Palmar indica a face anterior da mão (palma).'},
          {q:'A região cervical localiza-se entre:',options:['Craniana e torácica','Torácica e lombar','Lombar e sacral','Femoral e crural'],answer:0,explain:'A região cervical é o pescoço, entre crânio e tórax.'},
          {q:'A pelve óssea conecta:',options:['Membro superior ao tronco','Membro inferior ao tronco','Cabeça ao pescoço','Mão ao antebraço'],answer:1,explain:'A pelve faz a transição entre tronco e membros inferiores.'},
          {q:'A escápula compõe qual região?',options:['Cervical','Cintura escapular (torácica posterior)','Abdominal','Pélvica'],answer:1,explain:'A escápula situa-se na cintura escapular, porção posterior do tórax.'},
          {q:'A região lombar situa-se:',options:['Abaixo da pelve','Entre tórax e pelve, posteriormente','Na face anterior da coxa','Na face lateral do braço'],answer:1,explain:'A região lombar é a porção inferior das costas, entre costelas e pelve.'},
          {q:'O carpo corresponde à região do:',options:['Cotovelo','Punho','Joelho','Tornozelo'],answer:1,explain:'O carpo é o conjunto de ossos do punho, entre o antebraço e os metacarpos.'},
          {q:'O tarso corresponde à região do:',options:['Punho','Cotovelo','Tornozelo/retropé','Quadril'],answer:2,explain:'O tarso é o conjunto de ossos do tornozelo e retropé.'},
          {q:'A região axilar refere-se à:',options:['Virilha','Axila (sovaco)','Poplítea','Cubital'],answer:1,explain:'A região axilar corresponde à axila, área abaixo da articulação do ombro.'},
          {q:'A região poplítea localiza-se:',options:['Face anterior do joelho','Face posterior do joelho','Face lateral do quadril','Região lombar'],answer:1,explain:'A região poplítea é a fossa posterior ao joelho.'},
          {q:'A cintura pélvica é formada por:',options:['Fêmur e tíbia','Ossos coxais, sacro e cóccix','Vértebras lombares e sacro','Ilíaco e fêmur apenas'],answer:1,explain:'A cintura pélvica é formada pelos dois ossos coxais, sacro e cóccix.'},
          {q:'O olécrano é uma proeminência óssea localizada em:',options:['Joelho (patela)','Cotovelo (ulna proximal)','Tornozelo (maléolo)','Ombro (acrômio)'],answer:1,explain:'O olécrano é a proeminência posterior da ulna proximal, formando a ponta do cotovelo.'},
          {q:'A região inguinal (virilha) localiza-se entre:',options:['Abdome e coxa','Tórax e abdome','Coxa e perna','Pelve e lombar'],answer:0,explain:'A região inguinal está entre o abdome inferior e a coxa anterior.'},
          {q:'O hallux refere-se a:',options:['Polegar da mão','Hálux – primeiro dedo do pé','Tornozelo','Calcâneo'],answer:1,explain:'Hallux é o nome anatômico do primeiro dedo do pé (hálux).'},
          {q:'A região glútea corresponde anatomicamente à:',options:['Face anterior da coxa','Face posterior do quadril (nádegas)','Face medial da perna','Região lombar'],answer:1,explain:'A região glútea é a face posterior do quadril, formada principalmente pelos músculos glúteos.'},
          {q:'O cotovelo é a articulação entre:',options:['Rádio, ulna e carpo','Úmero, rádio e ulna','Úmero e escápula','Ulna e carpo'],answer:1,explain:'O cotovelo articula úmero (distal) com rádio e ulna (proximais).'},
        ]
      }
    ]
  },
  fisiologia: {
    label: 'Fisiologia',
    icon: '❤️',
    modules: [
      {
        id: 'sistema_cardiovascular',
        icon: '🫀',
        color: '#fff0f0',
        title: 'Sistema Cardiovascular',
        subtitle: 'Coração, ciclo cardíaco e circulação',
        questions: [
          {q:'A frequência cardíaca normal em repouso em adultos é de:',options:['20-40 bpm','60-100 bpm','110-130 bpm','150-180 bpm'],answer:1,explain:'A frequência cardíaca normal de repouso em adultos é de 60 a 100 batimentos por minuto.'},
          {q:'O nó sinoatrial (SA) é considerado o marcapasso do coração porque:',options:['Está no ventrículo esquerdo','Gera espontaneamente impulsos elétricos com maior frequência','Recebe sangue da aorta','É o maior nó cardíaco'],answer:1,explain:'O nó SA gera impulsos espontâneos com a maior frequência, determinando o ritmo cardíaco.'},
          {q:'A sístole ventricular corresponde à:',options:['Relaxamento dos ventrículos','Contração dos ventrículos e ejeção do sangue','Enchimento das câmaras','Relaxamento dos átrios'],answer:1,explain:'Sístole é a fase de contração ventricular e ejeção do sangue para as artérias.'},
          {q:'A diástole ventricular corresponde à:',options:['Contração e ejeção','Relaxamento e enchimento ventricular','Fechamento das válvulas aórticas','Contração atrial'],answer:1,explain:'Diástole é a fase de relaxamento ventricular e enchimento das câmaras.'},
          {q:'O ventrículo esquerdo bombeia sangue para:',options:['Pulmões (circulação pulmonar)','Átrio direito','Circulação sistêmica (aorta)','Veia cava'],answer:2,explain:'O ventrículo esquerdo ejeta sangue oxigenado pela aorta para a circulação sistêmica.'},
          {q:'O ventrículo direito bombeia sangue para:',options:['Aorta','Circulação pulmonar (artéria pulmonar)','Átrio esquerdo','Circulação sistêmica'],answer:1,explain:'O ventrículo direito ejeta sangue desoxigenado pela artéria pulmonar para os pulmões.'},
          {q:'A pressão arterial sistólica corresponde à pressão:',options:['Durante o relaxamento cardíaco','Durante a contração ventricular (ejeção)','Na veia cava','No átrio direito'],answer:1,explain:'A pressão sistólica é a pressão arterial máxima, registrada durante a sístole ventricular.'},
          {q:'Valores normais de pressão arterial em adultos (sistólica/diastólica):',options:['80/50 mmHg','120/80 mmHg','160/100 mmHg','200/120 mmHg'],answer:1,explain:'A pressão arterial normal é aproximadamente 120/80 mmHg em adultos saudáveis.'},
          {q:'O débito cardíaco é calculado por:',options:['Frequência cardíaca ÷ volume sistólico','Frequência cardíaca × volume sistólico','Pressão sistólica × diastólica','Volume sistólico ÷ pressão arterial'],answer:1,explain:'Débito cardíaco = FC × Volume sistólico. Em repouso, ~5 L/min.'},
          {q:'As válvulas atrioventriculares (mitral e tricúspide) impedem:',options:['Saída de sangue para as artérias','Refluxo do sangue dos ventrículos para os átrios','Entrada de sangue nos átrios','Passagem do sangue pelos capilares'],answer:1,explain:'As válvulas AV impedem o refluxo ventricular para os átrios durante a sístole.'},
          {q:'O som cardíaco B1 (primeira bulha) corresponde ao fechamento das válvulas:',options:['Aórtica e pulmonar','Mitral e tricúspide','Todas simultaneamente','Apenas aórtica'],answer:1,explain:'B1 corresponde ao fechamento das válvulas mitral e tricúspide no início da sístole.'},
          {q:'O retorno venoso ao coração é facilitado por:',options:['Contração arterial','Bomba muscular dos membros e respiração','Apenas gravidade','Ação das válvulas aórticas'],answer:1,explain:'O retorno venoso é favorecido pela bomba muscular, respiração e válvulas venosas.'},
          {q:'Taquicardia é definida como frequência cardíaca:',options:['Abaixo de 60 bpm','Acima de 100 bpm','Entre 60-80 bpm','Abaixo de 40 bpm'],answer:1,explain:'Taquicardia é FC acima de 100 bpm em adultos em repouso.'},
          {q:'Bradicardia é definida como frequência cardíaca:',options:['Abaixo de 60 bpm','Acima de 100 bpm','Entre 80-100 bpm','Acima de 150 bpm'],answer:0,explain:'Bradicardia é FC abaixo de 60 bpm em adultos em repouso.'},
          {q:'A fração de ejeção normal do ventrículo esquerdo é aproximadamente:',options:['20-30%','35-45%','55-70%','80-90%'],answer:2,explain:'A fração de ejeção normal é de 55-70%, indicando a porcentagem do volume ejetada por batimento.'},
          {q:'Durante o exercício físico, o débito cardíaco aumenta principalmente por aumento:',options:['Apenas da pressão diastólica','Da FC e do volume sistólico','Apenas do volume sanguíneo total','Da resistência vascular periférica'],answer:1,explain:'No exercício, FC e volume sistólico aumentam, elevando o débito cardíaco até ~20-25 L/min.'},
          {q:'O sistema nervoso simpático age sobre o coração:',options:['Reduzindo a FC e a força de contração','Aumentando a FC e a força de contração','Sem efeito na FC','Apenas sobre as válvulas cardíacas'],answer:1,explain:'O simpático libera noradrenalina, aumentando FC (cronotopia) e contratilidade (inotopia).'},
          {q:'O sistema nervoso parassimpático (vago) age sobre o coração:',options:['Aumentando FC','Reduzindo FC e condução AV','Aumentando o débito cardíaco','Sem efeito cardíaco'],answer:1,explain:'O parassimpático libera acetilcolina, reduzindo a FC e a velocidade de condução AV.'},
          {q:'A veia cava superior e inferior drenam sangue para:',options:['Ventrículo direito','Átrio direito','Átrio esquerdo','Ventrículo esquerdo'],answer:1,explain:'As veias cavas superior e inferior retornam sangue desoxigenado ao átrio direito.'},
          {q:'As veias pulmonares drenam sangue para:',options:['Átrio direito','Ventrículo direito','Átrio esquerdo','Aorta'],answer:2,explain:'As veias pulmonares trazem sangue oxigenado dos pulmões para o átrio esquerdo.'},
        ]
      },
      {
        id: 'sistema_respiratorio',
        icon: '🫁',
        color: '#f0f4ff',
        title: 'Sistema Respiratório',
        subtitle: 'Ventilação, volumes e trocas gasosas',
        questions: [
          {q:'A frequência respiratória normal em adultos em repouso é de:',options:['4-8 irpm','12-20 irpm','25-35 irpm','40-50 irpm'],answer:1,explain:'A frequência respiratória normal em adultos em repouso é de 12 a 20 incursões por minuto.'},
          {q:'O músculo principal da inspiração é:',options:['Intercostais externos','Diafragma','Esternocleidomastóideo','Escalenos'],answer:1,explain:'O diafragma é o principal músculo inspiratório, responsável por ~70% do trabalho ventilatório.'},
          {q:'A inspiração normal é um processo:',options:['Passivo','Ativo (requer contração muscular)','Apenas resultante da retração elástica','Exclusivamente dependente dos intercostais'],answer:1,explain:'A inspiração é ativa, pois requer contração do diafragma e intercostais externos.'},
          {q:'A expiração em repouso é predominantemente:',options:['Ativa (contração muscular)','Passiva (retração elástica pulmonar)','Dependente dos intercostais internos','Dependente do diafragma'],answer:1,explain:'Em repouso, a expiração é passiva, resultante da retração elástica do pulmão e da caixa torácica.'},
          {q:'O volume corrente (VC) é o volume de ar:',options:['Máximo inspirável','Inspirado/expirado em cada ciclo normal','Residual nos pulmões após expiração máxima','Total dos pulmões'],answer:1,explain:'Volume corrente é o volume trocado em cada respiração normal, ~500 mL em adultos.'},
          {q:'A capacidade vital (CV) é a soma de:',options:['Volume corrente + volume residual','Volume de reserva inspiratório + VC + volume de reserva expiratório','Todos os volumes pulmonares','Apenas volume residual + VC'],answer:1,explain:'CV = VRI + VC + VRE — é o volume máximo exalado após inspiração máxima.'},
          {q:'O volume residual (VR) é:',options:['O ar inspirado em repouso','O ar que permanece nos pulmões após expiração máxima','O ar de reserva para inspiração','O volume corrente de exercício'],answer:1,explain:'VR é o volume que permanece nos pulmões mesmo após expiração máxima forçada.'},
          {q:'A troca gasosa (hematose) ocorre nos:',options:['Brônquios','Traqueia','Alvéolos pulmonares','Bronquíolos terminais'],answer:2,explain:'A hematose (troca O₂/CO₂) ocorre nos alvéolos por difusão simples.'},
          {q:'O CO₂ é transportado no sangue principalmente como:',options:['CO₂ dissolvido apenas','Bicarbonato (HCO₃⁻)','Ligado à hemoglobina apenas','Oxiemoglobina'],answer:1,explain:'Cerca de 70% do CO₂ é transportado como bicarbonato no plasma.'},
          {q:'A oxiemoglobina é formada quando:',options:['O CO₂ liga-se à hemoglobina','O O₂ liga-se à hemoglobina','A hemoglobina libera O₂ nos tecidos','A hemoglobina capta CO₂'],answer:1,explain:'Oxiemoglobina é a hemoglobina ligada ao O₂, formada nos capilares alveolares.'},
          {q:'O centro respiratório principal localiza-se no:',options:['Córtex cerebral','Cerebelo','Bulbo (medula oblonga)','Mesencéfalo'],answer:2,explain:'O centro respiratório principal (grupos respiratórios dorsal e ventral) está no bulbo.'},
          {q:'O aumento de CO₂ no sangue (hipercapnia) causa:',options:['Redução da frequência respiratória','Aumento da frequência respiratória (hiperventilação)','Apneia','Bradicardia'],answer:1,explain:'Hipercapnia estimula quimiorreceptores, aumentando a ventilação para eliminar CO₂.'},
          {q:'A complacência pulmonar é definida como:',options:['Resistência ao fluxo de ar','Capacidade de distensão do pulmão em resposta a pressão','Volume residual do pulmão','Tensão superficial alveolar'],answer:1,explain:'Complacência é a facilidade de distensão pulmonar, ou seja, variação de volume por variação de pressão.'},
          {q:'O surfactante pulmonar é produzido pelos pneumócitos tipo II e sua função é:',options:['Aumentar a tensão superficial alveolar','Reduzir a tensão superficial e evitar colapso alveolar','Facilitar a difusão de CO₂','Aumentar a resistência das vias aéreas'],answer:1,explain:'O surfactante reduz a tensão superficial alveolar, prevenindo o colapso dos alvéolos.'},
          {q:'Durante o exercício, a ventilação aumenta principalmente para:',options:['Reduzir a FC','Eliminar o excesso de CO₂ produzido e fornecer O₂','Aumentar o volume residual','Reduzir a pressão arterial'],answer:1,explain:'No exercício, O₂ é mais consumido e CO₂ mais produzido, exigindo maior ventilação.'},
          {q:'A espirometria é um exame que avalia:',options:['Pressão arterial','Volumes e capacidades pulmonares','Frequência cardíaca','Saturação de O₂ apenas'],answer:1,explain:'A espirometria mede volumes e fluxos respiratórios, sendo fundamental na avaliação pulmonar.'},
          {q:'O VEF1 (volume expiratório forçado no 1° segundo) é um indicador de:',options:['Volume residual','Obstrução ao fluxo aéreo','Complacência pulmonar','Capacidade inspiratória'],answer:1,explain:'VEF1 reduzido indica obstrução ao fluxo aéreo, como em asma e DPOC.'},
          {q:'A SpO₂ (saturação periférica de O₂) normal em adultos saudáveis é:',options:['70-80%','85-90%','95-100%','60-70%'],answer:2,explain:'SpO₂ normal é de 95-100%. Valores abaixo de 90% indicam hipoxemia significativa.'},
          {q:'Qual músculos são recrutados na expiração forçada?',options:['Diafragma e escalenos','Reto abdominal e intercostais internos','Trapézio e peitoral maior','Só o diafragma'],answer:1,explain:'Na expiração forçada, o reto abdominal e intercostais internos contraem ativamente.'},
          {q:'A respiração diafragmática (abdominal) é incentivada na fisioterapia porque:',options:['Aumenta o trabalho respiratório','Otimiza a ventilação com menor gasto energético','Só é útil em pacientes graves','Reduz a complacência pulmonar'],answer:1,explain:'A respiração diafragmática promove melhor ventilação basal com menor trabalho muscular.'},
        ]
      },
      {
        id: 'sistema_muscular',
        icon: '💪',
        color: '#fff8e8',
        title: 'Fisiologia Muscular',
        subtitle: 'Contração, tipos de fibras e fadiga',
        questions: [
          {q:'A unidade funcional do músculo esquelético é:',options:['A fibra muscular inteira','O sarcômero','A miofibila completa','O músculo inteiro'],answer:1,explain:'O sarcômero, delimitado por duas linhas Z, é a unidade funcional e contrátil do músculo.'},
          {q:'As proteínas contráteis do músculo esquelético são:',options:['Actina e miosina','Tropomiosina e troponina','Colágeno e elastina','Titina e nebulina'],answer:0,explain:'Actina (filamento fino) e miosina (filamento grosso) são as proteínas contráteis principais.'},
          {q:'A teoria dos filamentos deslizantes explica que, durante a contração:',options:['Os filamentos se encurtam','Os filamentos deslizam entre si, encurtando o sarcômero','A miosina se dissolve','A actina se transforma em miosina'],answer:1,explain:'Na contração, filamentos de actina deslizam sobre miosina, encurtando o sarcômero sem alterar o comprimento dos filamentos.'},
          {q:'O cálcio (Ca²⁺) na contração muscular age principalmente:',options:['Diretamente na miosina','Ligando-se à troponina, liberando o sítio ativo da actina','Inibindo a actina','Ativando os filamentos de titina'],answer:1,explain:'Ca²⁺ liga-se à troponina C, deslocando a tropomiosina e expondo os sítios de ligação da actina à miosina.'},
          {q:'A fonte de energia imediata para a contração muscular é:',options:['Glicogênio','Gordura','ATP (adenosina trifosfato)','Creatina'],answer:2,explain:'ATP é a molécula diretamente utilizada pela miosina-ATPase para gerar força contrátil.'},
          {q:'As fibras musculares tipo I (lentas/oxidativas) são caracterizadas por:',options:['Alta força, fadiga rápida','Baixa resistência à fadiga, alta velocidade','Alta resistência à fadiga, metabolismo oxidativo','Alta glicólise anaeróbia'],answer:2,explain:'Fibras tipo I são ricas em mitocôndrias, resistentes à fadiga, ideais para atividades contínuas.'},
          {q:'As fibras musculares tipo II (rápidas/glicolíticas) são características de:',options:['Atividades aeróbias prolongadas','Contrações rápidas e potentes, com fadiga mais rápida','Alta resistência à fadiga','Metabolismo exclusivamente oxidativo'],answer:1,explain:'Fibras tipo II geram força rapidamente mas fatigam rápido, predominando em atividades explosivas.'},
          {q:'A contração isotônica concêntrica ocorre quando:',options:['O músculo contrai e encurta, vencendo a resistência','O músculo contrai e alonga sob carga','O comprimento não muda durante a contração','O músculo relaxa sem trabalho'],answer:0,explain:'Isotônica concêntrica: o músculo encurta enquanto gera tensão, vencendo a resistência.'},
          {q:'A contração isotônica excêntrica ocorre quando:',options:['O músculo encurta e gera força','O músculo alonga enquanto gera força (controla o movimento)','O comprimento não se altera','Não há produção de força'],answer:1,explain:'Na excêntrica, o músculo gera tensão enquanto é alongado (ex: descer escadas, agachamento controlado).'},
          {q:'A contração isométrica ocorre quando:',options:['O músculo encurta','O músculo alonga','O comprimento muscular não muda, mas há produção de tensão','Não há ativação muscular'],answer:2,explain:'Na contração isométrica, o comprimento muscular permanece constante enquanto há produção de tensão.'},
          {q:'O mecanismo responsável pelo relaxamento muscular é:',options:['Liberação de Ca²⁺ pelo retículo sarcoplasmático','Recaptação ativa de Ca²⁺ pelo retículo sarcoplasmático','Inativação da actina','Desnaturação da miosina'],answer:1,explain:'O relaxamento ocorre quando a Ca²⁺-ATPase recapta o cálcio para o retículo sarcoplasmático.'},
          {q:'A fadiga muscular periférica resulta principalmente de:',options:['Apenas hipoglicemia','Acúmulo de metabólitos, depleção de ATP e alterações iônicas na fibra muscular','Dano neurológico central','Redução da frequência cardíaca'],answer:1,explain:'Fadiga periférica envolve acúmulo de Pi, H⁺, depleção de glicogênio e alterações no Ca²⁺.'},
          {q:'A enervação de um músculo pelo nervo motor ocorre na estrutura chamada:',options:['Fuso muscular','Junção neuromuscular (placa motora)','Órgão tendinoso de Golgi','Corpúsculo de Meissner'],answer:1,explain:'A junção neuromuscular é o ponto de comunicação entre o neurônio motor e a fibra muscular.'},
          {q:'A acetilcolina (ACh) é o neurotransmissor que:',options:['Inibe a contração muscular','Inicia o potencial de ação na fibra muscular desencadeando a contração','Recapta o cálcio','Liga-se à miosina diretamente'],answer:1,explain:'ACh liberada na placa motora liga-se a receptores nicotínicos, gerando potencial de ação na fibra.'},
          {q:'O fuso muscular é um receptor sensorial que detecta:',options:['Tensão no tendão','Comprimento e variações no comprimento muscular','Pressão superficial','Temperatura muscular'],answer:1,explain:'O fuso muscular detecta o comprimento e a velocidade de variação do comprimento muscular.'},
          {q:'O órgão tendinoso de Golgi (OTG) detecta:',options:['Comprimento muscular','Tensão no tendão (força gerada pelo músculo)','Pressão articular','Temperatura'],answer:1,explain:'O OTG detecta tensão/força no tendão e ativa reflexo de inibição autogênica.'},
          {q:'O princípio do tamanho (Henneman) na ativação de unidades motoras determina que:',options:['As maiores unidades motoras são ativadas primeiro','As menores unidades motoras (tipo I) são recrutadas primeiro','Todas as unidades são ativadas simultaneamente','Só unidades tipo II são recrutadas'],answer:1,explain:'Pelo princípio do tamanho, neurônios menores (unidades lentas, tipo I) são recrutados primeiro.'},
          {q:'O EPOC (consumo excessivo de oxigênio pós-exercício) refere-se ao:',options:['Redução do VO₂ após exercício','Aumento do consumo de O₂ após o esforço para restaurar homeostase','Débito de O₂ apenas durante o exercício','Saturação de O₂ no músculo'],answer:1,explain:'EPOC é o O₂ extra consumido após exercício para restaurar ATP, glicogênio, temperatura e remover lactato.'},
          {q:'O VO₂máx representa:',options:['Volume de CO₂ expirado em repouso','Capacidade máxima de consumo de oxigênio durante exercício intenso','Volume sistólico máximo','Frequência respiratória máxima'],answer:1,explain:'VO₂máx é o índice de aptidão cardiorrespiratória máxima, medida em mL/kg/min.'},
          {q:'Rigor mortis ocorre porque, após a morte:',options:['Os músculos são inibidos pelo sistema nervoso','Não há ATP para romper as pontes cruzadas actina-miosina, causando rigidez','O cálcio é removido das fibras rapidamente','As proteínas contráteis se degradam imediatamente'],answer:1,explain:'Sem ATP, as pontes cruzadas não se dissociam, causando rigidez cadavérica (rigor mortis).'},
        ]
      }
    ]
  }
};
