const AREAS = {
  anatomia: {
    label: 'Anatomia',
    icon: '🩻',
    modules: [
      {
        id: 'planos_eixos',
        icon: '📐',
        color: '#e8f6ef',
        title: 'Planos e Eixos',
        subtitle: 'Posição anatômica, planos e movimentos',
        questions: [
          {q:'A posição anatômica padrão descreve o indivíduo:',options:['Deitado em decúbito dorsal','Em pé, face para frente, palmas para frente','Sentado com joelhos a 90°','Deitado em decúbito ventral'],answer:1,explain:'Em pé, olhando para frente, membros ao lado do corpo e palmas voltadas anteriormente.'},
          {q:'Qual plano divide o corpo em porções anterior e posterior?',options:['Sagital','Transversal','Frontal (coronal)','Oblíquo'],answer:2,explain:'O plano frontal ou coronal divide o corpo em partes anterior e posterior.'},
          {q:'O plano sagital mediano divide o corpo em:',options:['Superior e inferior','Anterior e posterior','Direita e esquerda','Proximal e distal'],answer:2,explain:'O plano sagital mediano divide o corpo em metades direita e esquerda simétricas.'},
          {q:'O plano transversal é também chamado de:',options:['Plano frontal','Plano horizontal','Plano coronal','Plano sagital'],answer:1,explain:'O plano transversal ou horizontal divide o corpo em partes superior e inferior.'},
          {q:'Flexão e extensão do joelho ocorrem no plano:',options:['Frontal','Transversal','Sagital','Oblíquo'],answer:2,explain:'Flexão e extensão são movimentos que ocorrem no plano sagital.'},
          {q:'Abdução e adução do quadril ocorrem no plano:',options:['Sagital','Frontal','Transversal','Horizontal'],answer:1,explain:'Abdução e adução ocorrem no plano frontal, afastando ou aproximando da linha média.'},
          {q:'Rotações (medial e lateral) ocorrem no plano:',options:['Sagital','Frontal','Transversal','Oblíquo'],answer:2,explain:'As rotações ocorrem em torno de um eixo longitudinal no plano transversal.'},
          {q:'O movimento de afastar o membro da linha média chama-se:',options:['Adução','Abdução','Rotação medial','Flexão'],answer:1,explain:'Abdução é o movimento de afastamento da linha média do corpo.'},
          {q:'O movimento de aproximar o membro da linha média chama-se:',options:['Abdução','Extensão','Adução','Rotação lateral'],answer:2,explain:'Adução é o movimento de aproximação em direção à linha média do corpo.'},
          {q:'O esterno está _______ em relação à coluna vertebral:',options:['Posterior','Lateral','Superior','Anterior'],answer:3,explain:'O esterno é anterior (ventral) em relação à coluna vertebral.'},
          {q:'O tornozelo é _______ em relação ao joelho:',options:['Proximal','Superior','Distal','Medial'],answer:2,explain:'O tornozelo está mais distante da raiz do membro, sendo distal ao joelho.'},
          {q:'Cranial indica posição:',options:['Mais próxima dos pés','Mais próxima da cabeça','Mais lateral','Mais posterior'],answer:1,explain:'Cranial (cefálico) indica proximidade em direção à cabeça.'},
          {q:'Lateral significa:',options:['Próximo à linha média','Afastado do plano mediano','Acima de outra estrutura','Distal'],answer:1,explain:'Lateral indica afastamento do plano mediano do corpo.'},
          {q:'Medial significa:',options:['Afastado da linha média','Próximo à linha média','Inferior','Posterior'],answer:1,explain:'Medial indica proximidade à linha média do corpo.'},
          {q:'Ipsilateral significa:',options:['No lado oposto','No mesmo lado do corpo','Na linha média','Distal'],answer:1,explain:'Ipsilateral refere-se a estruturas do mesmo lado do corpo.'},
          {q:'Contralateral significa:',options:['No mesmo lado','No lado oposto','Superior','Proximal'],answer:1,explain:'Contralateral refere-se a estruturas de lados opostos do corpo.'},
          {q:'O eixo em torno do qual ocorrem flexão e extensão é:',options:['Longitudinal','Ântero-posterior','Médio-lateral (transverso)','Oblíquo'],answer:2,explain:'Flexão e extensão ocorrem em torno do eixo médio-lateral (transverso).'},
          {q:'Supinação do antebraço é um movimento que ocorre no plano:',options:['Sagital','Frontal','Transversal','Coronal'],answer:2,explain:'Supinação e pronação são rotações que ocorrem no plano transversal.'},
          {q:'Qual termo indica estrutura mais próxima da superfície corporal?',options:['Profundo','Superficial','Medial','Distal'],answer:1,explain:'Superficial indica proximidade à superfície externa do corpo.'},
          {q:'O plano sagital paralelo ao mediano, mas deslocado lateralmente, é chamado de:',options:['Plano sagital mediano','Plano parassagital','Plano coronal','Plano horizontal'],answer:1,explain:'Planos sagitais que não passam pela linha média são chamados parassagitais.'},
        ]
      },
      {
        id: 'acidentes_osseos',
        icon: '🦴',
        color: '#f4fff2',
        title: 'Acidentes Ósseos',
        subtitle: 'Proeminências, depressões e forames',
        questions: [
          {q:'Saliências ósseas de inserção de tendões e ligamentos são chamadas de:',options:['Fossas','Côndilos','Tuberosidades','Forames'],answer:2,explain:'Tuberosidades são saliências rugosas para inserção muscular e ligamentar.'},
          {q:'Pequena proeminência óssea arredondada:',options:['Túber','Cabeça','Tubérculo','Espinha'],answer:2,explain:'Tubérculo é uma pequena saliência óssea arredondada.'},
          {q:'Superfície articular arredondada no final de osso longo:',options:['Epicôndilo','Côndilo','Crista','Linha'],answer:1,explain:'Côndilos são superfícies articulares arredondadas que se articulam com outros ossos.'},
          {q:'Abertura óssea para passagem de vasos e nervos:',options:['Fossa','Sulco','Forame','Espinha'],answer:2,explain:'Forame é a abertura óssea que permite passagem de estruturas neurovasculares.'},
          {q:'Depressão alongada em um osso:',options:['Fissura','Sulco','Espinha','Linha'],answer:1,explain:'Sulco é uma depressão alongada percorrida por tendões, vasos ou nervos.'},
          {q:'Grande proeminência óssea do fêmur proximal:',options:['Côndilo','Cabeça','Trocanter','Tubérculo'],answer:2,explain:'O fêmur possui grande e pequeno trocanter, grandes proeminências proximais.'},
          {q:'Porção esférica articular de ossos como úmero e fêmur:',options:['Cabeça','Fissura','Linha','Crista'],answer:0,explain:'A cabeça é a porção esférica articular de ossos longos como úmero e fêmur.'},
          {q:'Proeminência óssea estreita e pontiaguda:',options:['Linha','Crista','Espinha','Tuberosidade'],answer:2,explain:'Espinha óssea é uma projeção fina e pontiaguda.'},
          {q:'Área ampla e levemente elevada para inserção muscular:',options:['Tuberosidade','Fossa','Cabeça','Fissura'],answer:0,explain:'Tuberosidade é uma grande elevação rugosa para inserção muscular.'},
          {q:'Cavidade rasa e alargada em um osso:',options:['Fossa','Forame','Sulco','Crista'],answer:0,explain:'Fossas são depressões rasas, como a fossa supraespinhal da escápula.'},
          {q:'Processo vertebral palpável posteriormente ao longo da coluna:',options:['Côndilo occipital','Processo espinhoso','Cabeça do fêmur','Tubérculo maior'],answer:1,explain:'Os processos espinhosos projetam-se posteriormente e são palpáveis ao longo da coluna.'},
          {q:'Pequenas superfícies articulares planas das vértebras torácicas:',options:['Facetas articulares','Tubérculos','Trocanteres','Linhas'],answer:0,explain:'Facetas articulares são superfícies planas para articulação costo-vertebral.'},
          {q:'O acrômio é um exemplo de:',options:['Tubérculo','Processo','Forame','Fossa'],answer:1,explain:'O acrômio é um processo da escápula que forma o ponto mais alto do ombro.'},
          {q:'O sulco intertubercular do úmero abriga:',options:['Nervo radial','Tendão do bíceps braquial (cabeça longa)','Veia basílica','Nervo mediano'],answer:1,explain:'O sulco intertubercular (bicipital) abriga o tendão da cabeça longa do bíceps.'},
          {q:'A crista ilíaca é um exemplo de:',options:['Sulco','Forame','Crista','Côndilo'],answer:2,explain:'A crista ilíaca é uma crista óssea superior do osso ilíaco, palpável lateralmente.'},
          {q:'O processo estilóide é encontrado em:',options:['Fêmur','Rádio e ulna distais','Tíbia proximal','Escápula'],answer:1,explain:'Processos estilóides são encontrados no rádio e na ulna distais.'},
          {q:'Qual acidente ósseo forma a goteira do nervo radial no úmero?',options:['Sulco intertubercular','Sulco do nervo radial (goteira de torção)','Forame supracondilar','Fossa coronoide'],answer:1,explain:'O sulco do nervo radial (goteira de torção) percorre a face posterior do úmero.'},
          {q:'O tubérculo maior (troquiter) do úmero é ponto de inserção de:',options:['Deltóide e peitoral maior','Manguito rotador (supraespinhal, infraespinhal, redondo menor)','Bíceps e coracobraquial','Tríceps braquial'],answer:1,explain:'O tubérculo maior recebe inserção dos músculos supraespinhal, infraespinhal e redondo menor.'},
          {q:'A sínfise púbica é classificada como qual tipo de acidente ósseo/articulação?',options:['Diartrose sinovial','Anfiartroses (sínfise)','Sutura','Gonfose'],answer:1,explain:'A sínfise púbica é uma anfiartroses com disco fibrocartilaginoso entre os ossos púbicos.'},
          {q:'O forame obturado é encontrado em qual osso?',options:['Sacro','Osso coxal (ilíaco)','Fêmur','Tíbia'],answer:1,explain:'O forame obturado é uma grande abertura no osso coxal, delimitada pelo púbis e ísquio.'},
        ]
      },
      {
        id: 'segmentos',
        icon: '🧍',
        color: '#eaf1ff',
        title: 'Segmentos Corporais',
        subtitle: 'Divisão e nomenclatura regional',
        questions: [
          {q:'A divisão básica do corpo humano inclui:',options:['Crânio, tórax e pelve apenas','Cabeça, pescoço, tronco e membros','Membros superiores e inferiores apenas','Tórax e abdome apenas'],answer:1,explain:'A divisão clássica inclui cabeça, pescoço, tronco (tórax, abdome, pelve) e membros.'},
          {q:'O tronco é composto por:',options:['Cabeça e pescoço','Tórax, abdome e pelve','Mãos e pés','Coxa e perna'],answer:1,explain:'Tronco compreende tórax, abdome e pelve/região glútea.'},
          {q:'O antebraço localiza-se entre:',options:['Braço e mão','Mão e ombro','Coxa e perna','Perna e pé'],answer:0,explain:'O antebraço está entre o braço (proximal) e a mão (distal).'},
          {q:'Anatomicamente, a perna localiza-se entre:',options:['Quadril e joelho','Joelho e tornozelo','Tornozelo e pé','Coxa e quadril'],answer:1,explain:'Perna é o segmento entre joelho e tornozelo. Entre quadril e joelho é a coxa.'},
          {q:'A região plantar refere-se à:',options:['Sola do pé','Dorso da mão','Face anterior da perna','Face posterior do tronco'],answer:0,explain:'Plantar refere-se à face inferior (sola) do pé.'},
          {q:'A região palmar corresponde à:',options:['Dorso do pé','Face anterior da mão','Face posterior da perna','Região cervical'],answer:1,explain:'Palmar indica a face anterior da mão (palma).'},
          {q:'A região cervical localiza-se entre:',options:['Craniana e torácica','Torácica e lombar','Lombar e sacral','Femoral e crural'],answer:0,explain:'A região cervical é o pescoço, entre crânio e tórax.'},
          {q:'A pelve óssea conecta:',options:['Membro superior ao tronco','Membro inferior ao tronco','Cabeça ao pescoço','Mão ao antebraço'],answer:1,explain:'A pelve faz a transição entre tronco e membros inferiores.'},
          {q:'A escápula compõe qual região?',options:['Cervical','Cintura escapular (torácica posterior)','Abdominal','Pélvica'],answer:1,explain:'A escápula situa-se na cintura escapular, porção posterior do tórax.'},
          {q:'A região lombar situa-se:',options:['Abaixo da pelve','Entre tórax e pelve, posteriormente','Na face anterior da coxa','Na face lateral do braço'],answer:1,explain:'A região lombar é a porção inferior das costas, entre costelas e pelve.'},
          {q:'O carpo corresponde à região do:',options:['Cotovelo','Punho','Joelho','Tornozelo'],answer:1,explain:'O carpo é o conjunto de ossos do punho, entre o antebraço e os metacarpos.'},
          {q:'O tarso corresponde à região do:',options:['Punho','Cotovelo','Tornozelo/retropé','Quadril'],answer:2,explain:'O tarso é o conjunto de ossos do tornozelo e retropé.'},
          {q:'A região axilar refere-se à:',options:['Virilha','Axila (sovaco)','Poplítea','Cubital'],answer:1,explain:'A região axilar corresponde à axila, área abaixo da articulação do ombro.'},
          {q:'A região poplítea localiza-se:',options:['Face anterior do joelho','Face posterior do joelho','Face lateral do quadril','Região lombar'],answer:1,explain:'A região poplítea é a fossa posterior ao joelho.'},
          {q:'A cintura pélvica é formada por:',options:['Fêmur e tíbia','Ossos coxais, sacro e cóccix','Vértebras lombares e sacro','Ilíaco e fêmur apenas'],answer:1,explain:'A cintura pélvica é composta pelos ossos coxais, sacro e cóccix.'},
          {q:'O braço (segmento do membro superior) situa-se entre:',options:['Antebraço e mão','Ombro e cotovelo','Punho e dedos','Cotovelo e punho'],answer:1,explain:'O braço está entre o ombro (proximal) e o cotovelo (distal).'},
          {q:'A coxa situa-se entre:',options:['Joelho e tornozelo','Quadril e joelho','Pé e perna','Tornozelo e pelve'],answer:1,explain:'A coxa é o segmento entre o quadril (proximal) e o joelho (distal).'},
          {q:'A região inguinal (virilha) localiza-se:',options:['Entre tórax e abdome','Entre abdome e coxa','Na fossa poplítea','Na região axilar'],answer:1,explain:'A região inguinal situa-se na junção entre abdome e coxa.'},
          {q:'Os dedos da mão são chamados de:',options:['Falanges','Metacarpos','Carpos','Artelhos'],answer:0,explain:'Os dedos da mão são formados pelas falanges (proximal, média e distal). Artelhos são os dedos do pé.'},
          {q:'A nuca corresponde à região:',options:['Anterior do pescoço','Posterior do pescoço','Lateral do crânio','Anterior do tórax'],answer:1,explain:'A nuca é a face posterior do pescoço, região occipital inferior.'},
        ]
      },
      {
        id: 'coluna_vertebral',
        icon: '🔗',
        color: '#fff8e8',
        title: 'Coluna Vertebral',
        subtitle: 'Vértebras, curvaturas e estruturas',
        questions: [
          {q:'Quantas vértebras compõem a coluna vertebral adulta normalmente?',options:['24 móveis + sacro + cóccix','33 a 34 no total','Apenas 24','30 no total'],answer:1,explain:'A coluna possui 7 cervicais + 12 torácicas + 5 lombares + sacro (5 fundidas) + cóccix (3-4 fundidas), totalizando 33-34.'},
          {q:'Qual é a curvatura fisiológica da região lombar?',options:['Cifose','Escoliose','Lordose','Retificação'],answer:2,explain:'A região lombar apresenta lordose (curvatura convexa anterior) como curvatura fisiológica normal.'},
          {q:'A curvatura torácica fisiológica é classificada como:',options:['Lordose','Cifose','Escoliose','Hiperlordose'],answer:1,explain:'A região torácica apresenta cifose fisiológica (convexidade posterior).'},
          {q:'O atlas é a vértebra:',options:['C2','C1','L1','T1'],answer:1,explain:'O atlas é C1, primeira vértebra cervical, que se articula com o crânio (côndilos occipitais).'},
          {q:'O áxis (C2) possui uma projeção chamada:',options:['Processo espinhoso','Dente (processo odontóide)','Tubérculo anterior','Processo transverso'],answer:1,explain:'O áxis possui o dente (processo odontóide) que se articula com o atlas, permitindo rotação da cabeça.'},
          {q:'O disco intervertebral é formado por:',options:['Cartilagem hialina e osso','Anel fibroso e núcleo pulposo','Ligamento e fáscia','Periósteo e medula'],answer:1,explain:'O disco intervertebral é composto pelo anel fibroso (anulus fibrosus) na periferia e núcleo pulposo no centro.'},
          {q:'Qual região vertebral possui processos transversos com forames para a artéria vertebral?',options:['Torácica','Lombar','Cervical','Sacral'],answer:2,explain:'As vértebras cervicais possuem forames transversários por onde passa a artéria vertebral.'},
          {q:'O sacro é formado pela fusão de quantas vértebras?',options:['3','4','5','6'],answer:2,explain:'O sacro é formado pela fusão de 5 vértebras sacrais, formando um osso triangular.'},
          {q:'Qual ligamento percorre toda a face anterior dos corpos vertebrais?',options:['Ligamento longitudinal posterior','Ligamento longitudinal anterior','Ligamento amarelo','Ligamento interespinhoso'],answer:1,explain:'O ligamento longitudinal anterior percorre a face anterior de todos os corpos vertebrais, limitando a extensão.'},
          {q:'A vértebra proeminente (C7) é caracterizada por ter:',options:['Processo espinhoso curto e bífido','Processo espinhoso longo e não bífido, palpável','Forame transversário grande','Corpo vertebral menor'],answer:1,explain:'C7 tem processo espinhoso longo, único e proeminente, facilmente palpável na base do pescoço.'},
        ]
      },
      {
        id: 'musculos_membro_inferior',
        icon: '🦵',
        color: '#f0e8ff',
        title: 'Músculos do Membro Inferior',
        subtitle: 'Quadril, coxa, perna e pé',
        questions: [
          {q:'Qual é o maior e mais superficial músculo glúteo, responsável pela extensão do quadril?',options:['Glúteo médio','Glúteo mínimo','Glúteo máximo','Piriforme'],answer:2,explain:'O glúteo máximo é o maior músculo do glúteo, principal extensor e rotador lateral do quadril.'},
          {q:'O músculo iliopsoas é o principal:',options:['Extensor do quadril','Flexor do quadril','Abdutor do quadril','Rotador medial do quadril'],answer:1,explain:'O iliopsoas (ilíaco + psoas maior) é o principal flexor do quadril, com origem na coluna lombar e ilíaco.'},
          {q:'O quadríceps femoral é composto por quantas porções?',options:['Dois','Três','Quatro','Cinco'],answer:2,explain:'O quadríceps é formado por: reto femoral, vasto lateral, vasto medial e vasto intermédio — quatro porções.'},
          {q:'A principal função do quadríceps femoral é:',options:['Flexão do joelho','Extensão do joelho','Abdução do quadril','Flexão plantar do tornozelo'],answer:1,explain:'O quadríceps é o principal extensor do joelho, fundamental para marcha, corrida e subida de escadas.'},
          {q:'Os músculos isquiotibiais são formados por:',options:['Reto femoral, vasto lateral e vasto medial','Bíceps femoral, semitendíneo e semimembranoso','Gastrocnêmio, sóleo e plantar','Glúteo máximo, médio e mínimo'],answer:1,explain:'Os isquiotibiais são: bíceps femoral, semitendíneo e semimembranoso — extensores do quadril e flexores do joelho.'},
          {q:'Qual músculo é conhecido como "alfaiate" por cruzar o membro de lateral para medial?',options:['Grácil','Sartório','Tensor da fáscia lata','Pectíneo'],answer:1,explain:'O sartório é o músculo mais longo do corpo; cruza obliquamente a coxa e realiza flexão, abdução e rotação lateral do quadril.'},
          {q:'O tendão de Aquiles é a inserção do(s):',options:['Quadríceps femoral','Isquiotibiais','Tríceps sural (gastrocnêmio + sóleo)','Tibial anterior'],answer:2,explain:'O tendão de Aquiles (calcâneo) é formado pela união dos tendões do gastrocnêmio e do sóleo, inserindo-se no calcâneo.'},
          {q:'A principal ação do músculo tibial anterior é:',options:['Flexão plantar e eversão','Dorsiflexão e inversão do pé','Flexão dos artelhos','Abdução do hálux'],answer:1,explain:'O tibial anterior realiza dorsiflexão (flexão dorsal) e inversão do pé, sendo o principal músculo da face anterior da perna.'},
          {q:'O glúteo médio e o glúteo mínimo são os principais responsáveis por:',options:['Extensão e rotação lateral do quadril','Abdução do quadril e estabilização pélvica na marcha','Flexão do joelho','Flexão plantar'],answer:1,explain:'Glúteo médio e mínimo são os principais abdutores do quadril e estabilizam a pelve durante a fase de apoio unipodal na marcha.'},
          {q:'Qual músculo realiza flexão plantar e é essencial para a propulsão na marcha e corrida?',options:['Tibial anterior','Fibular longo','Gastrocnêmio','Extensor longo dos dedos'],answer:2,explain:'O gastrocnêmio (e o sóleo) realiza flexão plantar com força, sendo essencial para a propulsão durante a marcha e corrida.'},
          {q:'O músculo grácil pertence ao grupo dos:',options:['Extensores do joelho','Adutores da coxa','Abdutores do quadril','Dorsiflexores do tornozelo'],answer:1,explain:'O grácil é um músculo adutor da coxa, localizado na face medial, que também auxilia na flexão do joelho.'},
          {q:'Os músculos fibulares (peroneiros) longo e curto realizam principalmente:',options:['Inversão e dorsiflexão','Eversão do pé e flexão plantar','Extensão dos artelhos','Abdução do quadril'],answer:1,explain:'Os fibulares longo e curto são os principais eversores do pé e auxiliam na flexão plantar.'},
          {q:'Qual músculo da coxa tem origem no trocanter menor do fêmur?',options:['Glúteo máximo','Iliopsoas','Pectíneo','Quadrado femoral'],answer:1,explain:'O iliopsoas insere-se no trocanter menor do fêmur após sua origem na coluna lombar (psoas) e fossa ilíaca (ilíaco).'},
          {q:'A síndrome do trato iliotibial (banda IT) envolve especialmente qual músculo?',options:['Vasto lateral','Tensor da fáscia lata e glúteo máximo','Sartório','Pectíneo'],answer:1,explain:'A banda iliotibial é um espessamento da fáscia lata formado pelas inserções do tensor da fáscia lata e glúteo máximo.'},
          {q:'O músculo poplíteo tem como função principal:',options:['Extensão do joelho','Rotação lateral da tíbia com o joelho estendido / desbloqueio do joelho','Flexão plantar','Dorsiflexão'],answer:1,explain:'O poplíteo "desbloqueia" o joelho realizando rotação medial da tíbia (ou lateral do fêmur) para iniciar a flexão.'},
        ]
      },
    ]
  },
  fisiologia: {
    label: 'Fisiologia',
    icon: '🫀',
    modules: [
      {
        id: 'cardiovascular',
        icon: '❤️',
        color: '#fff0f0',
        title: 'Sistema Cardiovascular',
        subtitle: 'Coração, circulação e pressão arterial',
        questions: [
          {q:'O débito cardíaco é definido como:',options:['Pressão sistólica menos diastólica','Volume sistólico multiplicado pela frequência cardíaca','Frequência cardíaca em repouso','Volume de sangue total do corpo'],answer:1,explain:'Débito cardíaco (DC) = Volume sistólico (VS) × Frequência cardíaca (FC). Representa o volume bombeado por minuto.'},
          {q:'A pressão arterial sistólica representa:',options:['Pressão durante o relaxamento ventricular','Pressão mínima nos vasos','Pressão durante a contração ventricular (sístole)','Resistência vascular periférica'],answer:2,explain:'A pressão sistólica é a pressão máxima nos vasos, gerada durante a contração (sístole) ventricular.'},
          {q:'Valores de pressão arterial considerados normais para adultos são:',options:['160/100 mmHg','140/90 mmHg','120/80 mmHg','100/60 mmHg'],answer:2,explain:'A pressão arterial normal é inferior a 120/80 mmHg. Valores ≥ 140/90 mmHg caracterizam hipertensão.'},
          {q:'O nó sinoatrial (NSA) é considerado o marcapasso cardíaco porque:',options:['Está localizado no ventrículo esquerdo','Gera impulsos elétricos espontâneos com maior frequência','É o maior nó do coração','Recebe sangue oxigenado diretamente'],answer:1,explain:'O NSA gera despolarizações espontâneas com frequência de 60-100 bpm, ditando o ritmo cardíaco.'},
          {q:'Durante o exercício físico, o débito cardíaco aumenta principalmente por:',options:['Redução da frequência cardíaca','Aumento do volume sistólico e da frequência cardíaca','Vasoconstrição generalizada','Redução do retorno venoso'],answer:1,explain:'No exercício, o aumento do DC se deve ao aumento do VS (pelo maior retorno venoso) e da FC (pelo sistema simpático).'},
          {q:'A circulação pulmonar conduz sangue:',options:['Do coração esquerdo para o corpo','Do coração direito para os pulmões e de volta ao coração esquerdo','Dos rins para o coração','Do intestino para o fígado'],answer:1,explain:'A circulação pulmonar (pequena circulação) leva sangue venoso do ventrículo direito aos pulmões para hematose e retorna ao átrio esquerdo.'},
          {q:'A sístole ventricular esquerda gera pressão que impulsiona o sangue para:',options:['Artéria pulmonar','Veia cava','Aorta','Artéria coronária direita'],answer:2,explain:'O ventrículo esquerdo ejeta sangue oxigenado pela válvula aórtica para a aorta, iniciando a circulação sistêmica.'},
          {q:'A frequência cardíaca de repouso em adultos saudáveis é normalmente:',options:['30-50 bpm','60-100 bpm','100-120 bpm','120-150 bpm'],answer:1,explain:'A frequência cardíaca normal de repouso em adultos é de 60 a 100 batimentos por minuto.'},
          {q:'O retorno venoso ao coração é facilitado principalmente por:',options:['Contração cardíaca apenas','Ação da bomba muscular, válvulas venosas e pressão negativa intratorácica','Pressão arterial alta','Vasoconstrição das artérias'],answer:1,explain:'O retorno venoso depende da bomba muscular (contração dos músculos), válvulas venosas que impedem refluxo e pressão negativa na inspiração.'},
          {q:'A resistência vascular periférica total (RVP) influencia principalmente:',options:['Frequência cardíaca','Volume sistólico','Pressão arterial diastólica','Hematócrito'],answer:2,explain:'A RVP é o principal determinante da pressão diastólica. Quando os vasos se contraem (vasoconstrição), a RVP e a pressão diastólica aumentam.'},
        ]
      },
      {
        id: 'respiratorio',
        icon: '🫁',
        color: '#e8f4ff',
        title: 'Sistema Respiratório',
        subtitle: 'Ventilação, troca gasosa e mecânica respiratória',
        questions: [
          {q:'O principal músculo da inspiração é:',options:['Intercostais internos','Diafragma','Escalenos','Esternocleidomastoideo'],answer:1,explain:'O diafragma é o principal músculo inspiratório, responsável por cerca de 70-80% do volume de ar inspirado.'},
          {q:'A capacidade pulmonar total (CPT) é a soma de:',options:['Volume corrente e volume de reserva inspiratório','Todos os volumes pulmonares (CV + VR)','Apenas volume corrente e volume residual','Volume de reserva expiratório e volume residual'],answer:1,explain:'A CPT = Capacidade vital (CV) + Volume residual (VR), representando o total de ar nos pulmões após inspiração máxima.'},
          {q:'A troca gasosa entre alvéolos e capilares pulmonares ocorre por:',options:['Transporte ativo','Osmose','Difusão simples (gradiente de pressão parcial)','Filtração'],answer:2,explain:'O O₂ e CO₂ trocam entre alvéolos e sangue por difusão simples, movendo-se do local de maior para menor pressão parcial.'},
          {q:'Durante a expiração tranquila (passiva), ocorre:',options:['Contração dos intercostais externos','Contração do diafragma','Relaxamento do diafragma e recuo elástico pulmonar','Aumento do volume torácico'],answer:2,explain:'A expiração tranquila é passiva: o diafragma relaxa e o recuo elástico dos pulmões reduz o volume torácico expulsando o ar.'},
          {q:'A frequência respiratória normal em adultos em repouso é de:',options:['6-8 irpm','12-20 irpm','25-30 irpm','30-40 irpm'],answer:1,explain:'A frequência respiratória normal em adultos é de 12 a 20 incursões respiratórias por minuto (irpm).'},
          {q:'O surfactante pulmonar é produzido por:',options:['Células de Clara','Macrófagos alveolares','Pneumócitos tipo II','Células caliciformes'],answer:2,explain:'O surfactante é produzido pelos pneumócitos tipo II (células alveolares tipo II), reduzindo a tensão superficial alveolar e prevenindo o colapso.'},
          {q:'Qual estrutura divide a traqueia nos brônquios principais direito e esquerdo?',options:['Epiglote','Carina','Glote','Bifurcação aórtica'],answer:1,explain:'A carina (carina traqueal) é a estrutura que divide a traqueia nos brônquios principais direito e esquerdo, em torno de T4-T5.'},
          {q:'O volume corrente (VC) em adultos em repouso é aproximadamente:',options:['150 mL','500 mL','1200 mL','3000 mL'],answer:1,explain:'O volume corrente normal em repouso é de aproximadamente 500 mL (0,5 L) por incursão respiratória.'},
          {q:'Hipóxia é definida como:',options:['Excesso de CO₂ no sangue','Redução do O₂ nos tecidos','Aumento do O₂ nos tecidos','Ausência de CO₂ no sangue'],answer:1,explain:'Hipóxia é a redução da oferta ou utilização de oxigênio pelos tecidos, podendo ser hipoxêmica, anêmica, circulatória ou histotóxica.'},
          {q:'Durante o exercício intenso, a ventilação aumenta principalmente para:',options:['Reduzir a frequência cardíaca','Eliminar o excesso de CO₂ e manter o pH sanguíneo','Aumentar a pressão arterial','Reduzir a temperatura corporal'],answer:1,explain:'O aumento da ventilação no exercício é estimulado pelo acúmulo de CO₂ e queda do pH (acidose), mantendo a homeostase ácido-base.'},
          {q:'O espaço morto anatômico refere-se a:',options:['Alvéolos sem perfusão sanguínea','Volume de ar nas vias aéreas que não participa da troca gasosa','Pulmão colapsado','Capacidade residual funcional'],answer:1,explain:'O espaço morto anatômico (~150 mL) é o volume de ar que ocupa as vias aéreas condutoras (traqueia, brônquios) sem realizar troca gasosa.'},
          {q:'A oxiemoglobina é formada quando:',options:['O CO₂ se liga à hemoglobina','O O₂ se liga à hemoglobina nos pulmões','A hemoglobina perde o ferro','O CO se liga à hemoglobina'],answer:1,explain:'Oxiemoglobina (HbO₂) é formada quando o O₂ se liga reversivelmente à hemoglobina nos capilares pulmonares.'},
          {q:'A capacidade vital (CV) representa:',options:['Volume de ar residual nos pulmões','Volume máximo de ar expirado após inspiração máxima','Volume corrente em repouso','Volume de reserva expiratório apenas'],answer:1,explain:'A CV = VRI + VC + VRE, representando o volume máximo de ar que pode ser expirado após uma inspiração máxima.'},
          {q:'Qual músculo acessório da respiração eleva as costelas durante inspiração forçada?',options:['Diafragma','Intercostais internos','Esternocleidomastoideo e escalenos','Reto abdominal'],answer:2,explain:'Na inspiração forçada, o esternocleidomastoideo eleva o esterno e os escalenos elevam as primeiras costelas, ampliando a caixa torácica.'},
          {q:'A pressão parcial de O₂ no ar alveolar é aproximadamente:',options:['21 mmHg','100 mmHg','160 mmHg','40 mmHg'],answer:1,explain:'A pressão parcial de O₂ nos alvéolos é de aproximadamente 100 mmHg, menor que no ar atmosférico (160 mmHg) pelo CO₂ alveolar.'},
        ]
      },
    ]
  },
  biomecanica: {
    label: 'Biomecânica',
    icon: '⚙️',
    modules: [
      {
        id: 'articulacoes',
        icon: '🔩',
        color: '#e8fff4',
        title: 'Tipos de Articulações',
        subtitle: 'Classificação, estrutura e mobilidade',
        questions: [
          {q:'As articulações são classificadas funcionalmente em:',options:['Fibrosas, cartilaginosas e sinoviais','Sinartroses, anfiartroses e diartroses','Uniaxiais, biaxiais e multiaxiais','Planas, esféricas e em dobradiça'],answer:1,explain:'Funcionalmente: sinartroses (imóveis), anfiartroses (semimóveis) e diartroses (livremente móveis).'},
          {q:'A articulação sinovial é caracterizada por:',options:['Ausência de cavidade articular','Presença de cavidade articular, líquido sinovial e cápsula fibrosa','União por tecido fibroso denso','Presença apenas de fibrocartilagem'],answer:1,explain:'As diartroses (sinoviais) possuem cavidade articular preenchida por líquido sinovial, cápsula fibrosa e cartilagem hialina nas superfícies.'},
          {q:'Qual tipo de articulação sinovial permite movimento em todos os planos (multiaxial)?',options:['Dobradiça (gínglimo)','Plana (artródia)','Esférica (enartroses)','Trocoide (pivô)'],answer:2,explain:'A articulação esférica (enartroses), como quadril e ombro, é multiaxial, permitindo movimentos em todos os planos.'},
          {q:'A articulação do joelho é classificada como:',options:['Articulação plana','Articulação em dobradiça modificada (gínglimo)','Articulação esférica','Articulação em sela'],answer:1,explain:'O joelho é uma articulação em dobradiça modificada (gínglimo), com movimentos predominantes de flexão e extensão no plano sagital.'},
          {q:'As suturas do crânio são exemplos de:',options:['Diartroses','Anfiartroses','Sinartroses fibrosas','Articulações sinoviais'],answer:2,explain:'As suturas são sinartroses fibrosas — articulações imóveis unidas por tecido fibroso denso, encontradas entre os ossos do crânio.'},
          {q:'O líquido sinovial tem como principal função:',options:['Produzir cartilagem hialina','Lubrificar e nutrir a cartilagem articular','Conectar ossos por colágeno','Produzir osteoblastos'],answer:1,explain:'O líquido sinovial lubrifica a articulação, reduz o atrito e nutre a cartilagem hialina avascular por difusão.'},
          {q:'A articulação atlantoaxial (C1-C2) é do tipo:',options:['Esférica','Em sela','Trocoide (pivô)','Dobradiça'],answer:2,explain:'A articulação atlantoaxial é do tipo trocoide (pivô), permitindo rotação axial da cabeça (dizer "não").'},
          {q:'A articulação carpometacarpal do polegar é do tipo:',options:['Plana','Em sela (selar)','Esférica','Dobradiça'],answer:1,explain:'A articulação carpometacarpal do polegar é em sela (selar), permitindo flexão, extensão, abdução, adução e oposição.'},
          {q:'A sínfise púbica é classificada como:',options:['Diartrose sinovial','Sinartrose fibrosa','Anfiartroses cartilaginosa (sínfise)','Articulação em dobradiça'],answer:2,explain:'A sínfise púbica é uma anfiartroses cartilaginosa com disco de fibrocartilagem, permitindo pequena mobilidade.'},
          {q:'O menisco do joelho é composto por:',options:['Cartilagem hialina','Fibrocartilagem','Tecido ósseo esponjoso','Tecido sinovial'],answer:1,explain:'Os meniscos medial e lateral do joelho são formados por fibrocartilagem, aumentando a congruência articular e absorvendo impacto.'},
          {q:'A articulação do cotovelo (úmero-ulnar) é classificada como:',options:['Esférica','Plana','Dobradiça (gínglimo)','Em sela'],answer:2,explain:'A articulação úmero-ulnar é uma dobradiça (gínglimo) uniaxial, permitindo apenas flexão e extensão.'},
          {q:'Os ligamentos têm como principal função biomecânica:',options:['Gerar força de contração','Unir osso a músculo','Estabilizar articulações e limitar movimentos excessivos','Produzir líquido sinovial'],answer:2,explain:'Os ligamentos conectam osso a osso, estabilizando as articulações e limitando amplitude excessiva de movimento.'},
          {q:'Qual estrutura reveste a superfície articular das diartroses, reduzindo o atrito?',options:['Periósteo','Cartilagem hialina','Fibrocartilagem','Membrana sinovial'],answer:1,explain:'A cartilagem hialina reveste as superfícies articulares das diartroses, fornecendo superfície lisa e reduzindo o atrito.'},
          {q:'A articulação glenoumeral (ombro) sacrifica estabilidade em favor de:',options:['Rigidez','Amplitude de movimento','Resistência à compressão','Produção de líquido sinovial'],answer:1,explain:'O ombro é a articulação mais móvel do corpo; sua rasa cavidade glenoidal sacrifica estabilidade óssea em troca de grande amplitude de movimento.'},
          {q:'A bursa articular tem como função principal:',options:['Produzir cartilagem','Reduzir o atrito entre tendões/músculos e ossos','Conectar ligamentos','Estabilizar meniscos'],answer:1,explain:'As bursas são sacos com líquido sinovial que reduzem o atrito entre tendões, músculos e proeminências ósseas.'},
        ]
      },
      {
        id: 'alavancas',
        icon: '⚖️',
        color: '#fffbe8',
        title: 'Alavancas e Forças',
        subtitle: 'Princípios mecânicos aplicados ao movimento humano',
        questions: [
          {q:'Uma alavanca é composta por:',options:['Força, resistência e atrito','Ponto de apoio (fulcro), força (potência) e resistência (carga)','Massa, velocidade e aceleração','Torque, inércia e gravidade'],answer:1,explain:'Toda alavanca possui: fulcro (ponto de apoio), força motora (potência) e resistência (carga a ser movida).'},
          {q:'Na alavanca de 1ª classe, o fulcro está:',options:['Entre a força e a resistência','Entre o fulcro e a resistência','Na extremidade do sistema','Do mesmo lado da força e resistência'],answer:0,explain:'Na alavanca de 1ª classe (interfixa), o fulcro está entre a força e a resistência. Exemplo: balanço e cabeça sobre a coluna.'},
          {q:'Qual é o exemplo clássico de alavanca de 2ª classe no corpo humano?',options:['Flexão do cotovelo','Elevação do calcanhar (ponta dos pés)','Extensão do joelho','Flexão do pescoço'],answer:1,explain:'Na elevação do calcanhar, o fulcro é o metatarso, a resistência é o peso corporal e a força é o tríceps sural — alavanca de 2ª classe (interpotente).'},
          {q:'Na alavanca de 3ª classe, a força está:',options:['Entre a resistência e o fulcro','Entre o fulcro e a resistência','Na extremidade oposta ao fulcro','No mesmo ponto do fulcro'],answer:1,explain:'Na alavanca de 3ª classe (interresistente), a força está entre o fulcro e a resistência. É a mais comum no corpo humano.'},
          {q:'A flexão do cotovelo pelo bíceps braquial é um exemplo de alavanca de:',options:['1ª classe','2ª classe','3ª classe','Não é uma alavanca'],answer:2,explain:'Na flexão do cotovelo, o fulcro é o cotovelo, a força é o bíceps (entre fulcro e resistência) e a resistência é o antebraço/mão — alavanca de 3ª classe.'},
          {q:'Torque é definido como:',options:['Força dividida pela distância','Força multiplicada pelo braço de momento (distância perpendicular ao fulcro)','Massa vezes aceleração','Pressão sobre uma superfície'],answer:1,explain:'Torque (momento de força) = Força × Braço de momento. Representa a capacidade de uma força causar rotação em torno de um eixo.'},
          {q:'Quando o braço de momento muscular aumenta, o torque:',options:['Diminui','Permanece igual','Aumenta','Torna-se zero'],answer:2,explain:'Torque = Força × Braço de momento. Se o braço de momento aumenta com a mesma força, o torque aumenta proporcionalmente.'},
          {q:'O centro de massa do corpo humano em posição anatômica está aproximadamente:',options:['Na altura do esterno','À altura de S2, anterior ao sacro','No umbigo','Na altura do quadril'],answer:1,explain:'O centro de massa do corpo humano adulto situa-se aproximadamente à altura de S2, levemente anterior ao sacro, variando com a posição.'},
          {q:'A vantagem mecânica de uma alavanca é calculada como:',options:['Resistência dividida pela força','Braço de momento da força dividido pelo braço de momento da resistência','Força vezes resistência','Torque dividido pela massa'],answer:1,explain:'Vantagem mecânica = Braço de momento da força / Braço de momento da resistência. VM > 1 indica vantagem; VM < 1 indica desvantagem mecânica.'},
          {q:'A maioria das alavancas musculoesqueléticas do corpo humano apresenta:',options:['Vantagem mecânica (VM > 1)','Desvantagem mecânica (VM < 1), priorizando velocidade e amplitude','Vantagem mecânica neutra (VM = 1)','VM variável sem padrão'],answer:1,explain:'A maioria das alavancas do corpo é de 3ª classe com VM < 1, o que significa desvantagem de força, mas ganho de velocidade e amplitude de movimento.'},
          {q:'Qual lei de Newton é fundamental para entender o equilíbrio estático no corpo humano?',options:['1ª Lei (inércia)','2ª Lei (F = ma)','3ª Lei (ação e reação)','Lei da gravitação universal'],answer:0,explain:'A 1ª Lei de Newton (inércia) explica o equilíbrio estático: um corpo em repouso permanece em repouso quando a soma das forças e torques é zero.'},
          {q:'A base de suporte influencia o equilíbrio porque:',options:['Determina a força muscular máxima','Uma base maior aumenta a estabilidade ao manter o centro de massa sobre ela','Reduz o peso corporal','Aumenta o torque muscular'],answer:1,explain:'Quanto maior e mais ampla a base de suporte, mais estável o corpo, pois o centro de massa tem mais área para se manter projetado sobre ela.'},
          {q:'No movimento angular, a velocidade linear de um ponto é:',options:['Igual à velocidade angular','A velocidade angular dividida pelo raio','A velocidade angular multiplicada pelo raio (v = ω × r)','Independente do raio'],answer:2,explain:'v = ω × r: a velocidade linear aumenta com o raio. Por isso, a mão (maior raio) move-se mais rápido que o cotovelo em rotação do ombro.'},
          {q:'A força de reação do solo (FRS) durante a marcha normal é aproximadamente:',options:['50% do peso corporal','100% do peso corporal na fase de apoio','120-150% do peso corporal no pico de apoio','300% do peso corporal'],answer:1,explain:'Durante a marcha tranquila, a FRS varia de cerca de 80% a 120% do peso corporal. Na corrida, pode atingir 2-3 vezes o peso corporal.'},
          {q:'O braço de momento de uma força muscular é a distância:',options:['Entre origem e inserção do músculo','Perpendicular entre a linha de ação da força e o eixo de rotação articular','Entre o músculo e o osso','Do fulcro até a resistência ao longo do segmento'],answer:1,explain:'O braço de momento (lever arm) é a distância perpendicular entre a linha de ação da força e o eixo de rotação — determina o torque produzido.'},
        ]
      },
    ]
  },
};
